name: Rust

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Install the nightly toolchain for esp32c3 (riscv32imc-esp-espidf) targets
      run:  rustup install nightly
    - name: Add rust-src for the nightly toolchain
      run:  rustup component add rust-src --toolchain nightly
    - name: Install toolchain dependencies
      run:  apt-get update && apt-get install -y vim nano git curl gcc ninja-build cmake libudev-dev python3 python3-pip libusb-1.0-0 libssl-dev pkg-config libtinfo5 llvm-dev libclang-dev clang
    - name: Install the Espressif toolchain
      run:  cargo install cargo-generate cargo-espflash espmonitor bindgen ldproxy
    - name: Build
      run:  cargo build --verbose
